### ISSUE TITLE
Major Locality Issue - Assets only fully work for who placed it

### ISSUE THREAD

**Issue by RemoteControlledArty** [RemoteControlledArty/RemoteControlledArtillery#10]
Issues likely caused by locality:
-driver not reacting to WASD
-gun laying resetting when releasing control
-targets selected on datalink panel not being highlighted by rectangle
-sometimes artillery computer is not disabling
-seats not being locked correctly on ICV/IFV/FSV/MBT

Potential fix:
-maybe change locality/ownership to who is currently remote controlling / sitting in it
https://community.bistudio.com/wiki/setOwner
https://community.bistudio.com/wiki/setGroupOwner

https://community.bistudio.com/wiki/Multiplayer_Scripting
http://killzonekid.com/arma-scripting-tutorials-locality/
https://forums.bohemia.net/forums/topic/173817-how-to-manage-units-locality-change-in-mp/

**Comment by realfluffyuwu** [comment]
Might be an idea to see when [ControlsShifted](https://community.bistudio.com/wiki/Arma_3:_Mission_Event_Handlers#ControlsShifted) is fired, might be able to use that to determine when the player takes control of the UAV.

Another Shot in the dark is just starkly listening for the [Action](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers/inGameUISetEventHandler#Action)

**Comment by Tapawingo** [comment]
>- driver not reacting to WASD

Issue has been narrowed down to be the vehicles effectiveCommander being set to the zeus. A workaround is to set the remote player as the leader of the UAV group, but this will of course create other issues so another solution should be seeked.

We tried using [setEffectiveCommander](https://community.bistudio.com/wiki/setEffectiveCommander) to force the remote player, but it did not work, the effectiveCommander was not set.

**Comment by RemoteControlledArty** [comment]
Testing results of the dev version:
-removing the if local check from IFV etc had no impact on the driver reacting to WASD

-removing the engine off script in the IFV etc init had no impact on the driver reacting to WASD

-disabling the engine off script for remote controlling had no impact on the driver reacting to WASD with the Howitzer

-disabling the script that sets autonomous to off when being in the artillery UI, made the Howitzers turret visibly turn & run raise again to other players (before other players didnt see the animation), it had no impact on the driver reacting to WASD

**Comment by RemoteControlledArty** [comment]
Are maybe the "commanding= ;" values of driver and gunner set up wrong?
They work in SP, but maybe need other values in MP?

*Edit: Tested multiple different setups, all worked in SP, but none of them had an effect on drivability in MP when the vehicle was given to a player by zeus.

https://community.bistudio.com/wiki/Turret_Config_Reference#commanding_=_1
